### ISSUE TITLE
possibility for MIT license

### ISSUE THREAD

**Issue by Hliii** [maincold2/FFNeRV#2]
The work is very exciting and impressive! 
I wander if it would be possible to obtain an MIT license from your repository? I am sure your work will be of great benefit to many people. And it will be very nice of you to do that.

**Comment by maincold2** [comment]
I appreciate your interest!
However, our code is partly based on NeRV which may not be under an MIT license.
I'm not sure whether we have a right to provide the license in this case.

**Comment by Hliii** [comment]
Thank you for getting back to me. I reached out to the author of NeRV and they have kindly granted us permission to use their code in MPEG evaluation experiments. I was wondering if you would also be willing to grant us permission to use your code for the same purpose? If needed, we can connect via email and I can provide proof of their agreement.

**Comment by maincold2** [comment]
We have updated our repositories to be under the MIT License. Nonetheless, we would like to notify you of our intention to pursue a patent for this content.
