### ISSUE TITLE
Scripts used for the calcualtion of BPP

### ISSUE THREAD

**Issue by bbdamodaran** [maincold2/FFNeRV#3]
Hi, thanks for the interesting work.

I have gone through your codes carefully; I wonder whether you can upload the script used for the calculation of the bits-per-pixel for the compression experiments.

Thanks, looking forward to hearing from you.

**Comment by maincold2** [comment]
We appreciate your interest in our work. We calculated the BPP using the formula provided below:

BPP = (model parameters) × (quantized bits) / (frame width) / (frame height) / (number of frames) × (efficiency of entropy coding)
e.g. 12M × 8 / 1920 / 1080 / 600 × 0.9

**Comment by bbdamodaran** [comment]
thanks for the description.
