### ISSUE TITLE
How to convert the.YUV format video into pictures?

### ISSUE THREAD

**Issue by Kris-Y-13** [maincold2/FFNeRV#6]
Great job!
I see that the dataset in the code is processed for each frame of the picture, may I ask, how to convert the.YUV format video into pictures?

**Comment by maincold2** [comment]
You can convert with ffmpeg:
<code>ffmpeg -i 𝑣𝑖𝑑𝑒𝑜.y4m 𝑣𝑖𝑑𝑒𝑜/f%05d.png</code>
More details are in Appendix A.
Thanks!

**Comment by Kris-Y-13** [comment]
Thank you!
